![imagen](./img/espectadores.jpg)

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Ejercicio creación de arrays en numpy</h3>

      
<ol>
    <li>Crea un array con 3 deportes que te gusten</li>
    <li>Accede al primer elemento y al último</li>
    <li>Comprueba los tipos de los datos</li>
    <li>Crea una secuencia de numeros del 10 al 0, con saltos de -0.5</li>
    <li>Crea una matriz de 5x2 con numeros enteros aleatorios comprendidos entre el 10 y el 20</li>
</ol>
         
 </td></tr>
</table>

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Ejercicio slicing</h3>

      
<ol>
    <li>Todos los elementos, pero de dos en dos</li>
    <li>Todos los elementos, pero de dos en dos, a partir del segundo item</li>
    <li>Todo, pero invertido</li>
    <li>Obtén los últimos dos items, y muéstralos invertidos</li>
    <li>Todo, excepto los ultimos dos items, y muéstralos invertidos.</li>
</ol>
         
 </td></tr>
</table>

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [27]:
import numpy as np

np.__version__


'1.26.4'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [33]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])

my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea una matriz 3x3, que sea todo a True

In [19]:
matrix_3 = np.full((3,3),True)

In [20]:
matrix_3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [21]:
impares = [x for x in my_array % 2 != 0]

impares

[False, True, False, True, False, True, False, True, False, True, False]

In [22]:
impares = []
for _ in my_array:
    if _ % 2 != 0:
        impares.append(_)

impares

[1, 3, 5, 7, 9]

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [23]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
menos = my_array % 2 != 0

my_array[menos] = -1

my_array
print(type(my_array))

<class 'numpy.ndarray'>


In [25]:
my_array = [x for x in my_array % 2 != 0]
type(my_array)

list

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [ ]:
nuevo_arra

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [34]:
print(my_array.ndim)
print(my_array.shape)
my_array

1
(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
my_array_7 = my_array.reshape((2,5))

my_array_7

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [37]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [42]:
a           #shape 2 filas, 5 columnas

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
b           #shape 2 filas, 5 columnas

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.concatenate([a,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [46]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [47]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [54]:
a = np.array([1,1,1,1,1,1,1,1,2,7])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [55]:
intersec = np.intersect1d(a,b)

intersec

array([2, 7])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [56]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7 (usando `my_array`)

In [60]:
my_array_9 = np.arange(0,10)
my_array_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
mul_10 = my_array_9 * 10

mul_10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [65]:
mul_10[0]

0

In [66]:
mul_10[-1]

90

In [71]:
my_array_9[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [80]:
my_matrix = np.array([[1,2,3],[3,2,1],[2,3,1]])
print('Dimensiones' , my_matrix.shape)
my_matrix


Dimensiones (3, 3)


array([[1, 2, 3],
       [3, 2, 1],
       [2, 3, 1]])

In [83]:
my_matrix_2 = np.matrix(my_matrix,int)
print('Dimensiones' , my_matrix_2.shape)
my_matrix_2

Dimensiones (3, 3)


matrix([[1, 2, 3],
        [3, 2, 1],
        [2, 3, 1]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [92]:
ejer_14 = np.arange(1,50,3)

list(ejer_14)

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [96]:
i = 1
sec = []
ejer_14_2 = [i for i in sec if i == 3]

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [103]:
ejer_15 = np.arange(4, 1, -0.25)
list(ejer_15)

[4.0, 3.75, 3.5, 3.25, 3.0, 2.75, 2.5, 2.25, 2.0, 1.75, 1.5, 1.25]

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes. Esto es, una única matriz

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?